"""empty message

Revision ID: 7ad0efc2af24
Revises: 71fcf93a7fb1
Create Date: 2024-04-16 19:16:58.732999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ad0efc2af24'
down_revision: Union[str, None] = '71fcf93a7fb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('dollars', sa.Integer(), server_default='4999', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'dollars')
    # ### end Alembic commands ###
