"""empty message

Revision ID: 800e69f37568
Revises: 7ad0efc2af24
Create Date: 2024-04-16 19:18:44.218191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '800e69f37568'
down_revision: Union[str, None] = '7ad0efc2af24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('win_dollars', sa.Integer(), server_default='0', nullable=True))
    op.add_column('users', sa.Column('wins', sa.Integer(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'wins')
    op.drop_column('users', 'win_dollars')
    # ### end Alembic commands ###
